Don't double-lock read-lock in Rename
It turns out the sync.RWMutex in golang is a non-starving variant.
This means that once an exclusive grab is waiting no further shared
grabs will be allowed. This is problematic if one thread, which grabs
the same lock twice, is racing against another thread which grabs the
lock exclusively. If the grabs are interleaved a deadlock will result.
This is shown by the following test program:

package main

import (
	"sync"
	"time"
)

func main() {
	locked := make(chan struct{})
	var lock sync.RWMutex

	lock.RLock()

	go func() {
		close(locked)
		lock.Lock()
		lock.Unlock()
	}()

	<-locked
	time.Sleep(1 * time.Second)
	lock.RLock()

	lock.RUnlock()
	lock.RUnlock()
}

Which fails with the following output:

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4200122ac)
        /usr/lib/golang/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc4200122a0)
        /usr/lib/golang/src/sync/rwmutex.go:50 +0x49
main.main()
        /home/travisb/go/src/github.com/aristanetworks/toys/lock.go:22 +0xc5

goroutine 4 [semacquire]:
sync.runtime_Semacquire(0xc4200122a8)
        /usr/lib/golang/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).Lock(0xc4200122a0)
        /usr/lib/golang/src/sync/rwmutex.go:98 +0x6e
main.main.func1(0xc42009a060, 0xc4200122a0)
        /home/travisb/go/src/github.com/aristanetworks/toys/lock.go:16 +0x39
created by main.main
        /home/travisb/go/src/github.com/aristanetworks/toys/lock.go:14 +0x93

This fixes a deadlock with the following goroutine stack traces:

goroutine 20051901 [semacquire, 23 minutes]:
sync.runtime_Semacquire(0xc420136554)
        /usr/lib/golang/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc420136548)
        /usr/lib/golang/src/sync/rwmutex.go:50 +0x49
github.com/aristanetworks/quantumfs/daemon.(*InodeCommon).RLockTree(0xc49e7aad80, 0x0)
        src/github.com/aristanetworks/quantumfs/daemon/inode.go:586 +0x32
github.com/aristanetworks/quantumfs/daemon.(*QuantumFs).RLockTreeGetInode(0xc4201361e0, 0xc424339590, 0x2985fe, 0xc80aae3c20, 0xc80aae3c01, 0x11475a0, 0xc421adbb00)
        src/github.com/aristanetworks/quantumfs/daemon/mux.go:670 +0x63
github.com/aristanetworks/quantumfs/daemon.(*QuantumFs).Rename(0xc4201361e0, 0xc960299388, 0xc62169c028, 0x8, 0xc62169c040, 0x8, 0xc400000005)
        src/github.com/aristanetworks/quantumfs/daemon/mux.go:1593 +0x49a
github.com/hanwen/go-fuse/fuse.doRename(0xc42027e540, 0xc960299200)
        src/github.com/hanwen/go-fuse/fuse/opcode.go:369 +0x7f
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc42027e540, 0xc960299200, 0xc960299200)
        src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x296
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc42027e540, 0xc559688101)
        src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x162
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
        src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x2be

goroutine 20051940 [semacquire, 23 minutes]:
sync.runtime_Semacquire(0xc420136550)
        /usr/lib/golang/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).Lock(0xc420136548)
        /usr/lib/golang/src/sync/rwmutex.go:98 +0x6e
github.com/aristanetworks/quantumfs/daemon.(*InodeCommon).LockTree(0xc91b8e6360, 0x0)
        src/github.com/aristanetworks/quantumfs/daemon/inode.go:581 +0x32
github.com/aristanetworks/quantumfs/daemon.(*QuantumFs).Link(0xc4201361e0, 0xcd56e25ec8, 0xc5ca149c60, 0xc, 0xcd56e25e38, 0xc400000005)
        src/github.com/aristanetworks/quantumfs/daemon/mux.go:1641 +0x480
github.com/hanwen/go-fuse/fuse.doLink(0xc42027e540, 0xcd56e25d40)
        src/github.com/hanwen/go-fuse/fuse/opcode.go:314 +0x6c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc42027e540, 0xcd56e25d40, 0xcd56e25d40)
        src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x296
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc42027e540, 0xc42027e501)
        src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x162
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
        src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x2be